#pragma once

#include "revolution/types.h"
#include <revolution.h>
#include <JGeometry.hpp>

class JMapInfoIter;

namespace MR {
    bool isValidInfo(const JMapInfoIter &);
    bool getObjectName(const char **, const JMapInfoIter &);
    bool isObjectName(const JMapInfoIter &, const char *);
    bool isExistJMapInfoArg0(const JMapInfoIter &);
    bool getJMapInfoShapeIdWithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoAreaIdWithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoTransLocal(const JMapInfoIter &, TVec3f *);
    bool getJMapInfoTrans(const JMapInfoIter &, TVec3f *);
    bool getJMapInfoRotateLocal(const JMapInfoIter  &, TVec3f *);
    bool getJMapInfoRotate(const JMapInfoIter &, TVec3f *);
    bool getJMapInfoScale(const JMapInfoIter &, TVec3f *);
    bool getJMapInfoMatrixFromRT(const JMapInfoIter &, TPos3f *);
    bool getJMapInfoV3f(const JMapInfoIter &, const char *, TVec3f *);
    bool getJMapInfoArg0WithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg0WithInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg0WithInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg1WithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg1WithInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg1WithInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg2WithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg2WithInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg2WithInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg3WithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg3WithInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg4WithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg5WithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg6WithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg7WithInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg7WithInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg0NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg0NoInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg0NoInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg1NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg1NoInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg1NoInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg2NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg2NoInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg2NoInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg3NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg3NoInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg3NoInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg4NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg4NoInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg4NoInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg5NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg5NoInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg5NoInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg6NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg6NoInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg6NoInit(const JMapInfoIter &, bool *);
    bool getJMapInfoArg7NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoArg7NoInit(const JMapInfoIter &, f32 *);
    bool getJMapInfoArg7NoInit(const JMapInfoIter &, bool *);
    bool getJMapInfoFollowID(const JMapInfoIter &, s32 *);
    bool getJMapInfoGroupID(const JMapInfoIter &, s32 *);
    bool getJMapInfoClippingGroupID(const JMapInfoIter &, s32 *);
    bool getJMapInfoDemoGroupID(const JMapInfoIter &, s32 *);
    bool getJMapInfoLinkID(const JMapInfoIter &, s32 *);
    bool getJMapInfoPriorityWithInit(const JMapInfoIter &, s32 *);
    bool isConnectedWithRail(const JMapInfoIter &);
    bool isExistStageSwitchA(const JMapInfoIter &);
    bool isExistStageSwitchB(const JMapInfoIter &);
    bool isExistStageSwitchAppear(const JMapInfoIter &);
    bool isExistStageSwitchDead(const JMapInfoIter &);
    bool isExistStageSwitchAwake(const JMapInfoIter &);
    bool isExistStageSwitchParam(const JMapInfoIter &);
    bool isExistMessageId(const JMapInfoIter &);
    bool isEqualObjectName(const JMapInfoIter &, const char *);
    bool getJMapInfoCameraSetID(const JMapInfoIter &, s32 *);
    bool getJMapInfoViewGroupID(const JMapInfoIter &, s32 *);
    bool getJMapInfoMessageID(const JMapInfoIter &, s32 *);
    bool getJMapInfoParamScale(const JMapInfoIter &, f32 *);
    s32 getJMapInfoDemoCastID(const JMapInfoIter &);
    const char* getJMapInfoDemoName(const JMapInfoIter &);
    const char* getJMapInfoTimeSheetName(const JMapInfoIter &);
    s32 getJMapInfoDemoGroupID(const JMapInfoIter &);
    s32 getJMapInfoDemoGroupLinkID(const JMapInfoIter &);
    bool getJMapInfoDemoSkip(const JMapInfoIter &);
    bool getJMapInfoRailArg(const JMapInfoIter &, const char *, s32 *);
    bool getJMapInfoRailArg0NoInit(const JMapInfoIter &, s32 *);
    bool getJMapInfoRailId(const JMapInfoIter &, s32 *);
    bool getJMapInfoNextLinkRailID(const JMapInfoIter &, s32 *);
    bool isEqualRailUsage(const JMapInfoIter &, const char *);
    void getRailPointPos0(const JMapInfoIter &, TVec3f *);
    void getRailPointPos1(const JMapInfoIter &, TVec3f *);
    void getRailPointPos2(const JMapInfoIter &, TVec3f *);
    bool isLoopRailPathIter(const JMapInfoIter &);
    bool getLinkObjID(const JMapInfoIter &, s32 *);
    bool getMapPartsID(const JMapInfoIter &, s32 *);
    bool getGeneratorID(const JMapInfoIter &, s32 *);
};
